### ISSUE TITLE
How to install the Loan Server?

### ISSUE THREAD

**Issue by unlimitedblade8** [cybertunnel/LoanShark#38]
Is there any tutorials for me to learn the LoanShark ?

**Comment by cybertunnel** [comment]
The wiki should hold all the information you need [here](https://github.com/cybertunnel/LoanShark/wiki). The [Kickstart Guide](https://github.com/cybertunnel/LoanShark/wiki/30---Kickstart-Guide) is a great way to begin integrating LoanShark.

We also have a growing channel, [#loanshark](https://macadmins.slack.com/messages/CHGFDDKST) on the [MacAdmin's Slack](https://macadmins.herokuapp.com/) instance.
